# Generated by Django 2.2.7 on 2019-12-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna_uno', models.CharField(max_length=200)),
                ('columna_dos', models.CharField(max_length=200)),
                ('columna_tres', models.CharField(max_length=200)),
                ('columna_cuatro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userGivenName', models.CharField(help_text='User given name', max_length=10)),
                ('userLastname', models.CharField(help_text='User Lastname', max_length=20)),
                ('userName', models.CharField(help_text='User name', max_length=10)),
                ('password', models.CharField(help_text='Password', max_length=12)),
                ('idRol', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.user')),
            ],
        ),
    ]
