# Generated by Django 2.2.7 on 2019-12-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla_test',
        ),
        migrations.AddField(
            model_name='almacen',
            name='estado',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='ubicacion',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
