# Generated by Django 2.2.7 on 2019-12-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20191205_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='encargado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.user'),
        ),
    ]
