# Generated by Django 2.2.7 on 2019-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20191205_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='estado',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
