# Generated by Django 2.2.7 on 2019-12-05 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20191205_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trabajo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idRol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
