# Generated by Django 2.2.6 on 2019-12-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('IdPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePermiso', models.CharField(max_length=200)),
                ('IdEstatus', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosAsignados',
            fields=[
                ('IdPermisoAsignado', models.AutoField(primary_key=True, serialize=False)),
                ('IdUsuario', models.IntegerField()),
                ('IdPermiso', models.IntegerField()),
                ('IdEstatus', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('IdRol', models.AutoField(primary_key=True, serialize=False)),
                ('NombreRol', models.CharField(max_length=200)),
                ('IdEstatus', models.BooleanField(default=1)),
            ],
        ),
    ]
