# Generated by Django 2.2.6 on 2019-12-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='CampoId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
